# Generated by Django 6.0.3 on 2026-03-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='priority',
            field=models.CharField(max_length=20),
        ),
    ]
